# Generated by Django 5.0.3 on 2024-03-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersData',
            fields=[
                ('userid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
